/** Интерфейсы */
import { GetTreeProps } from './interfaces';

/** Заглушка метода получения категорий */
export const TEST_TREE: GetTreeProps = {
  success: true,
  data: [
    {
      id: 6,
      name: 'Золото',
      price_multiplier: 1000,
      game_id: 3,
      created_at: 1555732503,
      updated_at: 1555732503,
      sort: 5,
      commission: 3,
      show_price: 1,
      show_count: 1,
      show_time: 1,
      multiple_sale: 1,
      status: 1,
      parent_id: null,
      is_instant_delivery: 0,
      is_allow_multiple_offers: null,
      isFinal: true,
    },
    {
      id: 7,
      name: 'Рейды',
      price_multiplier: 1,
      game_id: 3,
      created_at: 1555816711,
      updated_at: 1555816711,
      sort: 6,
      commission: 10,
      show_price: 0,
      show_count: 0,
      show_time: 0,
      multiple_sale: 0,
      status: 1,
      parent_id: null,
      is_instant_delivery: 0,
      is_allow_multiple_offers: null,
      isFinal: false,
      children: [
        {
          id: 8,
          name: "Дазар'Алор",
          price_multiplier: 1,
          game_id: 3,
          created_at: 1555817073,
          updated_at: 1555817073,
          sort: 1,
          commission: 10,
          show_price: 0,
          show_count: 0,
          show_time: 0,
          multiple_sale: 1,
          status: 1,
          parent_id: 7,
          is_instant_delivery: 0,
          is_allow_multiple_offers: null,
          isFinal: true,
        },
        {
          id: 9,
          name: 'Горнило штормов',
          price_multiplier: 1,
          game_id: 3,
          created_at: 1555919373,
          updated_at: 1555919373,
          sort: 3,
          commission: 10,
          show_price: 0,
          show_count: 1,
          show_time: 1,
          multiple_sale: 1,
          status: 1,
          parent_id: 7,
          is_instant_delivery: 0,
          is_allow_multiple_offers: null,
          isFinal: true,
        },
      ],
    },
    {
      id: 19,
      name: 'Серебро',
      price_multiplier: 1000,
      game_id: 3,
      created_at: 1559631163,
      updated_at: 1559631163,
      sort: 13,
      commission: 10,
      show_price: 1,
      show_count: 1,
      show_time: 1,
      multiple_sale: 1,
      status: 1,
      parent_id: null,
      is_instant_delivery: 0,
      is_allow_multiple_offers: 1,
      isFinal: true,
    },
    {
      id: 51,
      name: 'Серебро',
      price_multiplier: 1000,
      game_id: 3,
      created_at: 1573635179,
      updated_at: 1574063841,
      sort: 25,
      commission: 10,
      show_price: 1,
      show_count: 1,
      show_time: 1,
      multiple_sale: 1,
      status: 1,
      parent_id: null,
      is_instant_delivery: 0,
      is_allow_multiple_offers: null,
      isFinal: true,
    },
  ],
};
